### ISSUE TITLE
Raspberry Pi ZeroでWifi接続する場合の注意点

### ISSUE THREAD

**Issue by dfujii** [future-standard/cbeta#7]
- 推奨構成に入れているPlanex社製 GW-450D2（Wifiドングル）は現在、Raspberry Pi Zeroでは利用出来ません。
- この点について、今後修正をする予定です。（2016/8/3）

**Comment by h2suzuki** [comment]
2016/8/17 のアップデートで、Raspberry Pi Zero でも GW-450D2 を利用可能になりました。
